name: Tutorial
version: 1.0.0
api: 3.0.0
main: Tutorial\Main
author: xXNiceYT

commands:
  test:
    description: "TEST"
  lul:
    description: "LUL"
  feed:
    description: "Feed yourself"
  heal:
    description: "Heal yourself"
  fly:
    description: "Enable or disable fly"
  clearinv:
    description: "Clear your inventory"